# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Eight Suzuki" # chnage the title to your website's titel
weight = 1
