# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

# change the URLs of github and so on Githubなどの自分のアカウントURLに変更

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/eightsuzuki"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com/8Infu"

[social.params]
icon = "brand-twitter"
